#!/usr/bin/env node
/**
 * Increment Build Number Script
 * Runs before build to increment the build number
 * Build number is separate from version and increments on every build
 * Uses timestamp-based build number that works across deployments
 */

import { readFileSync, writeFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const projectRoot = join(__dirname, '..');
const packageJsonPath = join(projectRoot, 'package.json');
const buildNumberPath = join(projectRoot, '.build-number');

// Read package.json for version
const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf-8'));
const currentVersion = packageJson.version || '1.0.0';

// Get build number from multiple sources (for Vercel compatibility)
// Priority: Vercel build number env var > .build-number file > timestamp-based

let buildNumber;
const vercelBuildNumber = process.env.VERCEL_BUILD_ID ? parseInt(process.env.VERCEL_BUILD_ID.slice(-6), 16) : null;

if (vercelBuildNumber) {
  // Use Vercel's build ID (last 6 hex digits as decimal)
  buildNumber = vercelBuildNumber;
} else if (existsSync(buildNumberPath)) {
  // Try to read from file (local development)
  try {
    const content = readFileSync(buildNumberPath, 'utf-8').trim();
    buildNumber = parseInt(content, 10) || 1;
    buildNumber += 1; // Increment for next build
  } catch (e) {
    // Fallback to timestamp-based
    buildNumber = Math.floor(Date.now() / 1000) % 1000000;
  }
} else {
  // First build or no file - use timestamp-based
  // Use last 6 digits of timestamp (ensures uniqueness across builds)
  buildNumber = Math.floor(Date.now() / 1000) % 1000000;
  
  // If file doesn't exist, create it with current build number + 1 for next time
  try {
    writeFileSync(buildNumberPath, (buildNumber + 1).toString(), 'utf-8');
  } catch (e) {
    // Ignore if we can't write (e.g., read-only filesystem)
  }
}

// Write new build number for next local build (if we can)
if (!vercelBuildNumber) {
  try {
    writeFileSync(buildNumberPath, (buildNumber + 1).toString(), 'utf-8');
  } catch (e) {
    // Ignore if we can't write
  }
}

// Generate build info file
const buildInfoPath = join(projectRoot, 'src/utils/build-info.generated.ts');
const buildInfoContent = `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * This file is generated by scripts/increment-build.js on every build
 * Build Number: ${buildNumber}
 * Version: ${currentVersion}
 * Generated: ${new Date().toISOString()}
 */

export const BUILD_NUMBER = ${buildNumber};
export const APP_VERSION = '${currentVersion}';
export const BUILD_DATE = '${new Date().toISOString()}';

/**
 * Get formatted version string with build number
 */
export const getVersionString = (): string => {
  return \`v\${APP_VERSION} (build \${BUILD_NUMBER})\`;
};

/**
 * Get version string without build number
 */
export const getVersionOnly = (): string => {
  return \`v\${APP_VERSION}\`;
};

/**
 * Get build number only
 */
export const getBuildNumber = (): number => {
  return BUILD_NUMBER;
};
`;

writeFileSync(buildInfoPath, buildInfoContent, 'utf-8');

console.log(`🔨 Build number incremented: ${buildNumber - 1} → ${buildNumber}`);
console.log(`📦 Version: ${currentVersion}`);
console.log(`📝 Generated: src/utils/build-info.generated.ts`);
