#!/usr/bin/env node
/**
 * Inline Logo Script
 * Generates src/assets/logo.generated.ts with the logo as a base64 data URL.
 * Ensures the logo loads in iframes (no separate asset request).
 */

import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const projectRoot = join(__dirname, '..');
const logoPath = join(projectRoot, 'src/assets/logo.png');
const outPath = join(projectRoot, 'src/assets/logo.generated.ts');

const buf = readFileSync(logoPath);
const base64 = buf.toString('base64');
const dataUrl = `data:image/png;base64,${base64}`;

writeFileSync(
  outPath,
  `// Generated by scripts/inline-logo.js - do not edit\n/** Logo as base64 data URL (works in iframes). */\nexport default ${JSON.stringify(dataUrl)};\n`,
  'utf-8'
);

console.log('📷 Inlined logo into src/assets/logo.generated.ts');
